version: '3'

services:
  frontend:
    build: ./frontend
    stdin_open: true
    networks:
      - default
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - 5000:3000
    external_links:
      - api

  api:
    container_name: api
    build: ./api
    networks:
      - default
    volumes:
      - ./api:/usr/src/app
    ports:
      - 5001:8080
    external_links:
      - mongo
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'

networks:
  default:
