version: '3'

services:
  frontend:
    build: ./frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
      - /app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - api
  nginx:
    restart: always
    build: ./controller
    ports:
      - '5000:80'
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - app/node_modules
    ports:
      - '8080:8080'
    external_links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'
