version: '3.3'

services:
  frontend:
    container_name: frontend
    build: ./frontend
    stdin_open: true
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - '5000:3000'

  api:
    container_name: vinyllib-api
    container_name: my-web-container
    build: ./api
    volumes:
      - ./api:/usr/src/app
    ports:
      - '5001:8080'
    external_links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - '27017:27017'
