version: '3'
services:
  frontend:
    build: ./frontend
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - mern-app
  api:
    build: ./api
    ports:
      - '5000:8080'
    networks:
      - mern-app
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
